name: Deploy Demo

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER_DEMO }}
          username: ${{ secrets.SFTP_USER_DEMO }}
          password: ${{ secrets.SFTP_PASSWORD_DEMO }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
